# Generated by Django 5.1.6 on 2025-03-16 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the car make (minimum 2 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Enter a nickname for the auto', max_length=50)),
                ('mileage', models.IntegerField(help_text='Enter the mileage for the auto')),
                ('comments', models.CharField(blank=True, help_text='Optional comments about the auto', max_length=300)),
                ('make', models.ForeignKey(help_text='Select the make of the auto', on_delete=django.db.models.deletion.CASCADE, to='autos.make')),
            ],
        ),
    ]
